[package]
name = "ethereum-tx-sign"
version = "3.0.4"
description = "Allows you to model a raw ethereum transaction and sign it with your private key"
repository = "https://github.com/synlestidae/ethereum-tx-sign"
license = "MIT"
keywords = ["web3", "ethereum", "transaction", "sign"]
authors = ["Mate Antunovic <mateATantunovic.nz>"]
readme = "README.md"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tiny-keccak = { version = "2.0", features = ["keccak"] }
secp256k1 = {version = "0.19", features = ["recovery"] }
rlp = "0.5"
ethereum-types = "0.11.0"
num-traits = "0.2"
